---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    aws_region: "us-east-1"   # update your region here

  tasks:
  - name: get all instance info
    ec2_instance_info:
      region: "{{ aws_region }}"
    register: result

  - name: display result
    debug:
      msg: "{{ result.instances | map(attribute='instance_id') }}"
