---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: get all instance info
    ec2_instance_info:
    register: result
  
  - name: get instance id 
    set_fact: 
      anything: "{{ result['instances'] }}"
    register: filterd_result
  
  - name: get all ids
    vars:
      reduce_query: >-
        [].{
        instance_id: instance_id
        }
      names: "{{ anything | json_query(reduce_query)}}"
    register: result_names
    no_log: true
    debug:
      var: names

  - name: start ec2
    ec2_instance:
      instance_ids: "{{ result_names.names | map(attribute='instance_id') }}"
      state: "started"
