---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    aws_region: "us-east-1"   # update your region here

  tasks:
  - name: get all instance info
    amazon.aws.ec2_instance_info:
      region: "{{ aws_region }}"
    register: result

  - name: start ec2
    amazon.aws.ec2_instance:
      region: "{{ aws_region }}"
      instance_ids: "{{ result.instances | map(attribute='instance_id') }}"
      state: "started"