---
- hosts: localhost
  connection: local

  vars: 
    ids: 
    - i-0e54aa4fa6bb4b976

  tasks:
  - name: start ec2
    amazon.aws.ec2_instance:
      instance_ids: "{{ ids }}"
      state: "started"
