name: 'Ansible Deployment'

on:
  push:
    branches: [ "*" ]
  pull_request:

permissions:
  contents: read

jobs:
  ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-python@v2
      with:
        python-version: 3
    - name: configure environment
      run: |
        pip install boto3 botocore

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: virtual_machine_info.yml
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
